task:
  auto_cancellation: false
  main_install_script: |
    if [ $python == "nope" ]; then
      go get github.com/unarxiv/cvpm/cli
    fi
  env:
    PATH: /snap/bin:$PATH
    CIRRUS_WORKING_DIR: /go/src/github.com/unarxiv/CVPM
  matrix:
    - container:
        image: golang:latest
      only_if: $CIRRUS_TAG != ''
      deploy_script: curl -sL https://git.io/goreleaser | bash
      name: Deploy Job
      env:
        python: "nope"
    - container:
        image: golang:latest
      env:
        GOROOT: '/usr/local/go1.11'
        modulePath: '/go/src/github.com/unarxiv/CVPM'
      prep_script: |
        mkdir -p '$(GOPATH)/pkg'
        mkdir -p '$(modulePath)'
        shopt -s extglob
        mv !(gopath) '$(modulePath)'
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
        fi
      build_script: go build -v
      name: Golang Job
      env:
        python: "nope"
    - container:
        image: python:latest
      install_script: python3 -m pip install --upgrade setuptools wheel
      build_package_script: python3 setup.py sdist bdist_wheel
      wheel_artifacts:
        path: ./dist/*.whl
      artifacts:
        path: ./dist/**/**
      name: Python Job
      env:
        python: "yup"
