language: go
sudo: required
git:
  clone: quiet

env:
# needed for the snap pipe:
  - GO111MODULE=on

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make test-cli
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

go:
  - master

matrix:
  allow_failures:
    - go: tip

install: true

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true