name: cvpm
version: 0.0.3
summary: Computer Vision Package Manager
description: |
  CVPM is a package manager for computer vision. It helps you to download, install and run a computer vision service.
grade: devel # must be 'stable' to release into candidate/stable channels
#Golang needs access to r/w arbitrary files
confinement: classic

apps:
  cvpm:
    command: cvpm

parts:
  cvpm:
    after: [go]
    source: cli/
    plugin: go
    go-importpath: github.com/unarxiv/cvpm/cli