[package]
name="Face_utility"
base_image="python:3.6-slim-stretch"

[[solvers]]
name="Face_Detection"
class="face_utility/solver/FaceDetectionSolver"

[[solvers]]
name="Face_Landmark"
class="face_utility/solver/FaceLandmarkSolver"

[[solvers]]
name="Face_Encoding"
class="face_utility/solver/FaceEncodingSolver"